### PR TITLE
Add Harbor 1.6.0 blog post

### PR DESCRIPTION
**Pull request by jonasrosland**
This will add a blog post with details for the 1.6.0 release.

### CODE REVIEW

**Comment by jonasrosland** [comment]
The blog post contains the demo videos already, I think for a blog post that should be enough. We then link to the wiki page where more content could be added as needed.

See example of what it looks like live:
image

What do you think?

**Comment by jonasrosland** [comment]
I added links to the documentation where applicable.

**Comment by jonasrosland** [comment]
@steven-zou @hainingzhang Is this good to go now?

**Comment by clouderati** [comment]
Love it!

**Comment by clouderati** [comment]
Just regenerated the blog with your new post. Thanks again @jonasrosland!

**Pull request merged**
